name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

env:
  SLOW_MACHINE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        
      - name: Build
        run: make bins

      - name: Test
        run: make test

  integration-tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        test-vector: [bitcoin-cln, bitcoin-lnd, liquid-cln, liquid-lnd, misc-integration]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run tests
        run: nix-shell --run "make test-${{matrix.test-vector}}"